services:
  nginx:
    image: nginx:stable
    container_name: ojs-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ojs-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    depends_on:
      ojs:
        condition: service_started
      extractor:
        condition: service_started

  ojs:
    build:
      context: .
      dockerfile: ojs/Dockerfile
    container_name: ojs-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:80"
    environment:
      OJS_CLI_INSTALL: "0"
      TZ: Asia/Jakarta
      OJS_DB_HOST: postgres
      OJS_DB_DRIVER: pgsql
      OJS_DB_NAME: ${POSTGRES_DB}
      OJS_DB_USER: ${POSTGRES_USER}
      OJS_DB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ojs-files:/var/www/files
      - ojs-public:/var/www/html/public
      - ojs-plugins:/var/www/html/plugins
      - ojs-config:/var/www/html/config-vol
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ojs-network

  postgres:
    image: postgres:15
    container_name: ojs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ojs-network

  extractor:
    build:
      context: ./extractor
    container_name: traffic-extractor
    restart: unless-stopped
    environment:
      TZ: Asia/Jakarta
    ports:
      - "127.0.0.1:8081:8081"
    volumes:
      - ./extractor/requests.log:/app/requests.log
      - ./.env:/app/.env 
    networks:
      - ojs-network

volumes:
  postgres-data:
  ojs-files:
  ojs-public:
  ojs-plugins:
  ojs-config:

networks:
  ojs-network:
    driver: bridge
